In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('goalkeeping.csv')
df

,Player,Pos,Squad,Comp,Age,MP,Starts,Min,90s,GA,...,W,D,L,CS,CS%,PKatt,PKA,PKsv,PKm,Save%.1
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Adrián\Adrian,GK,Liverpool,eng Premier League,33.0,3.0,3.0,270.0,3.0,9.0,...,1.0,1.0,1.0,1.0,33.3,0.0,0.0,0.0,0.0,NaN
2,Rúnar Alex Rúnarsson\Runar-Alex-Runarsson,GK,Arsenal,eng Premier League,25.0,1.0,0.0,16.0,0.2,0.0,...,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,NaN
3,Alisson\Alisson,GK,Liverpool,eng Premier League,27.0,33.0,33.0,2970.0,33.0,32.0,...,18.0,8.0,7.0,10.0,30.3,8.0,4.0,1.0,3.0,20.0
4,Saturnin Allagbé\Saturnin-Allagbe,GK,Dijon,fr Ligue 1,26.0,12.0,12.0,1080.0,12.0,30.0,...,2.0,2.0,8.0,3.0,25.0,3.0,1.0,1.0,1.0,50.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,Rubén Yáñez\Ruben-Yanez,GK,Getafe,es La Liga,26.0,10.0,10.0,900.0,10.0,12.0,...,3.0,3.0,4.0,4.0,40.0,1.0,1.0,0.0,0.0,0.0
205,Yoel\Yoel,GK,Eibar,es La Liga,31.0,4.0,3.0,300.0,3.3,3.0,...,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
206,Robin Zentner\Robin-Zentner,GK,Mainz 05,de Bundesliga,25.0,31.0,31.0,2790.0,31.0,46.0,...,9.0,9.0,13.0,5.0,16.1,6.0,5.0,0.0,1.0,0.0
207,Ron-Robert Zieler\Ron-Robert-Zieler,GK,Köln,de Bundesliga,31.0,1.0,0.0,51.0,0.6,1.0,...,0.0,0.0,0.0,0.0,NaN,1.0,1.0,0.0,0.0,0.0
208,Jeroen Zoet\Jeroen-Zoet,GK,Spezia,it Serie A,29.0,7.0,7.0,603.0,6.7,12.0,...,3.0,1.0,3.0,1.0,14.3,3.0,3.0,0.0,0.0,0.0

In [3]:
# Remove blank first row
df.drop(index=0, axis=0, inplace=True)
df = df.reset_index(drop=True)

# Clean Player Name Column
for index, row in df.iterrows():
    end = row['Player'].find('\\')
    df.loc[index, 'Player'] = row['Player'][0:end]
    
df

,Player,Pos,Squad,Comp,Age,MP,Starts,Min,90s,GA,...,W,D,L,CS,CS%,PKatt,PKA,PKsv,PKm,Save%.1
0,Adrián,GK,Liverpool,eng Premier League,33.0,3.0,3.0,270.0,3.0,9.0,...,1.0,1.0,1.0,1.0,33.3,0.0,0.0,0.0,0.0,NaN
1,Rúnar Alex Rúnarsson,GK,Arsenal,eng Premier League,25.0,1.0,0.0,16.0,0.2,0.0,...,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,NaN
2,Alisson,GK,Liverpool,eng Premier League,27.0,33.0,33.0,2970.0,33.0,32.0,...,18.0,8.0,7.0,10.0,30.3,8.0,4.0,1.0,3.0,20.0
3,Saturnin Allagbé,GK,Dijon,fr Ligue 1,26.0,12.0,12.0,1080.0,12.0,30.0,...,2.0,2.0,8.0,3.0,25.0,3.0,1.0,1.0,1.0,50.0
4,Nícolas Andrade,GK,Udinese,it Serie A,32.0,2.0,2.0,180.0,2.0,5.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,Rubén Yáñez,GK,Getafe,es La Liga,26.0,10.0,10.0,900.0,10.0,12.0,...,3.0,3.0,4.0,4.0,40.0,1.0,1.0,0.0,0.0,0.0
204,Yoel,GK,Eibar,es La Liga,31.0,4.0,3.0,300.0,3.3,3.0,...,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
205,Robin Zentner,GK,Mainz 05,de Bundesliga,25.0,31.0,31.0,2790.0,31.0,46.0,...,9.0,9.0,13.0,5.0,16.1,6.0,5.0,0.0,1.0,0.0
206,Ron-Robert Zieler,GK,Köln,de Bundesliga,31.0,1.0,0.0,51.0,0.6,1.0,...,0.0,0.0,0.0,0.0,NaN,1.0,1.0,0.0,0.0,0.0
207,Jeroen Zoet,GK,Spezia,it Serie A,29.0,7.0,7.0,603.0,6.7,12.0,...,3.0,1.0,3.0,1.0,14.3,3.0,3.0,0.0,0.0,0.0

In [4]:
df.describe()

,Age,MP,Starts,Min,90s,GA,GA90,SoTA,Saves,Save%,W,D,L,CS,CS%,PKatt,PKA,PKsv,PKm,Save%.1
count,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,207.000000,208.000000,208.000000,208.000000,208.000000,201.000000,208.000000,208.000000,208.000000,208.000000,149.000000
mean,27.980769,17.735577,17.557692,1580.091346,17.557212,24.610577,1.487452,69.312500,47.399038,67.029469,6.548077,4.461538,6.548077,4.576923,22.682587,3.350962,2.658654,0.500000,0.192308,14.869128
std,4.949954,14.453065,14.576354,1304.004826,14.489718,21.333498,0.701380,60.281253,41.941406,14.906285,6.801364,4.182834,6.319787,4.691842,19.192205,3.292049,2.715819,0.767706,0.472978,18.459978
min,18.000000,1.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,24.000000,3.000000,3.000000,270.000000,3.000000,4.000000,1.030000,10.000000,7.000000,62.850000,1.000000,1.000000,1.000000,0.000000,7.700000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,28.000000,15.000000,15.000000,1350.000000,15.000000,20.000000,1.445000,54.000000,35.500000,68.200000,5.000000,3.000000,4.000000,3.000000,22.200000,3.000000,2.000000,0.000000,0.000000,9.100000
75%,31.250000,33.000000,32.250000,2961.000000,32.925000,43.000000,1.752500,124.250000,84.000000,72.900000,10.000000,8.000000,12.000000,8.000000,33.300000,6.000000,4.000000,1.000000,0.000000,25.000000
max,42.000000,38.000000,38.000000,3420.000000,38.000000,91.000000,4.520000,228.000000,161.000000,100.000000,27.000000,15.000000,29.000000,21.000000,100.000000,13.000000,13.000000,4.000000,3.000000,100.000000

In [5]:
# Delete Penalty Stats
df = df.drop(['PKatt', 'PKA', 'PKsv', 'PKm', 'Save%.1'], axis=1)
df

,Player,Pos,Squad,Comp,Age,MP,Starts,Min,90s,GA,GA90,SoTA,Saves,Save%,W,D,L,CS,CS%
0,Adrián,GK,Liverpool,eng Premier League,33.0,3.0,3.0,270.0,3.0,9.0,3.00,19.0,10.0,52.6,1.0,1.0,1.0,1.0,33.3
1,Rúnar Alex Rúnarsson,GK,Arsenal,eng Premier League,25.0,1.0,0.0,16.0,0.2,0.0,0.00,2.0,2.0,100.0,0.0,0.0,0.0,0.0,NaN
2,Alisson,GK,Liverpool,eng Premier League,27.0,33.0,33.0,2970.0,33.0,32.0,0.97,111.0,82.0,74.8,18.0,8.0,7.0,10.0,30.3
3,Saturnin Allagbé,GK,Dijon,fr Ligue 1,26.0,12.0,12.0,1080.0,12.0,30.0,2.50,64.0,35.0,54.7,2.0,2.0,8.0,3.0,25.0
4,Nícolas Andrade,GK,Udinese,it Serie A,32.0,2.0,2.0,180.0,2.0,5.0,2.50,7.0,2.0,28.6,1.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,Rubén Yáñez,GK,Getafe,es La Liga,26.0,10.0,10.0,900.0,10.0,12.0,1.20,30.0,19.0,63.3,3.0,3.0,4.0,4.0,40.0
204,Yoel,GK,Eibar,es La Liga,31.0,4.0,3.0,300.0,3.3,3.0,0.90,5.0,2.0,40.0,0.0,1.0,2.0,0.0,0.0
205,Robin Zentner,GK,Mainz 05,de Bundesliga,25.0,31.0,31.0,2790.0,31.0,46.0,1.48,135.0,93.0,69.6,9.0,9.0,13.0,5.0,16.1
206,Ron-Robert Zieler,GK,Köln,de Bundesliga,31.0,1.0,0.0,51.0,0.6,1.0,1.76,2.0,2.0,100.0,0.0,0.0,0.0,0.0,NaN
207,Jeroen Zoet,GK,Spezia,it Serie A,29.0,7.0,7.0,603.0,6.7,12.0,1.79,26.0,17.0,65.4,3.0,1.0,3.0,1.0,14.3

In [6]:
# Filla NaN values with 0
df = df.fillna(0)ions have new methods 'DataFrame.isna()' and 'DataFrame.notna()'

In [71]: df
Out[71]:
     a    b  c
0  NaN  7.0  0
df.describe()

,Age,MP,Starts,Min,90s,GA,GA90,SoTA,Saves,Save%,W,D,L,CS,CS%
count,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000
mean,27.980769,17.735577,17.557692,1580.091346,17.557212,24.610577,1.487452,69.312500,47.399038,66.707212,6.548077,4.461538,6.548077,4.576923,21.919231
std,4.949954,14.453065,14.576354,1304.004826,14.489718,21.333498,0.701380,60.281253,41.941406,15.579622,6.801364,4.182834,6.319787,4.691842,19.305382
min,18.000000,1.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,24.000000,3.000000,3.000000,270.000000,3.000000,4.000000,1.030000,10.000000,7.000000,62.650000,1.000000,1.000000,1.000000,0.000000,0.000000
50%,28.000000,15.000000,15.000000,1350.000000,15.000000,20.000000,1.445000,54.000000,35.500000,68.100000,5.000000,3.000000,4.000000,3.000000,21.600000
75%,31.250000,33.000000,32.250000,2961.000000,32.925000,43.000000,1.752500,124.250000,84.000000,72.900000,10.000000,8.000000,12.000000,8.000000,33.300000
max,42.000000,38.000000,38.000000,3420.000000,38.000000,91.000000,4.520000,228.000000,161.000000,100.000000,27.000000,15.000000,29.000000,21.000000,100.000000

In [7]:
advanced_df = pd.read_csv('advanced_goalkeeping.csv')

# Remove blank first row and reset index
advanced_df.drop(index=0, axis=0, inplace=True)
advanced_df = advanced_df.reset_index(drop=True)
advanced_df = advanced_df.drop(['Att.1', 'Thr', 'Launch%', 'AvgLen', 'Att.2', 'Launch%.1', 'AvgLen.1',], axis=1)

# Clean Player Name Column
for index, row in advanced_df.iterrows():
    end = row['Player'].find('\\')
    advanced_df.loc[index, 'Player'] = row['Player'][0:end]
    
advanced_df.describe()

,Age,90s,GA,PKA,FK,CK,OG,PSxG,PSxG/SoT,PSxG+/-,/90,Cmp,Att,Cmp%,Opp,Stp,Stp%,#OPA,#OPA/90,AvgDist
count,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,207.000000,208.000000,208.000000,208.000000,208.000000,207.000000,208.000000,208.000000,207.000000,208.000000,208.000000,206.000000
mean,27.980769,17.557212,24.610577,2.658654,0.370192,3.019231,0.740385,23.092308,0.309130,-0.753846,-0.064375,111.533654,271.538462,40.493237,153.067308,11.091346,6.592271,11.600962,0.639856,14.278155
std,4.949954,14.489718,21.333498,2.715819,0.615795,2.965114,1.026181,19.936826,0.099221,3.382048,0.395589,105.564683,255.851026,11.792323,131.776987,10.738271,4.541218,11.646956,0.512046,2.712889
min,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.010000,-14.100000,-2.230000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.000000
25%,24.000000,3.000000,4.000000,0.000000,0.000000,0.000000,0.000000,4.200000,0.270000,-2.100000,-0.220000,13.000000,33.500000,35.000000,23.000000,1.000000,4.800000,1.000000,0.330000,13.000000
50%,28.000000,15.000000,20.000000,2.000000,0.000000,2.000000,0.000000,18.050000,0.310000,-0.300000,-0.030000,85.500000,199.000000,40.900000,116.000000,8.000000,6.500000,8.000000,0.585000,14.300000
75%,31.250000,32.925000,43.000000,4.000000,1.000000,5.000000,1.000000,40.550000,0.340000,0.900000,0.100000,198.250000,473.500000,46.200000,282.500000,19.250000,8.950000,20.000000,0.832500,15.300000
max,42.000000,38.000000,91.000000,13.000000,3.000000,13.000000,6.000000,76.400000,0.900000,9.800000,1.410000,488.000000,1038.000000,100.000000,427.000000,42.000000,33.300000,53.000000,3.910000,31.000000

In [8]:
combined_df = df.merge(advanced_df)

In [9]:
combined_df

,Player,Pos,Squad,Comp,Age,MP,Starts,Min,90s,GA,...,/90,Cmp,Att,Cmp%,Opp,Stp,Stp%,#OPA,#OPA/90,AvgDist
0,Adrián,GK,Liverpool,eng Premier League,33.0,3.0,3.0,270.0,3.0,9.0,...,-0.36,12.0,32.0,37.5,29.0,2.0,6.9,1.0,0.33,13.2
1,Rúnar Alex Rúnarsson,GK,Arsenal,eng Premier League,25.0,1.0,0.0,16.0,0.2,0.0,...,0.50,0.0,3.0,0.0,4.0,0.0,0.0,0.0,0.00,17.5
2,Alisson,GK,Liverpool,eng Premier League,27.0,33.0,33.0,2970.0,33.0,32.0,...,0.18,127.0,275.0,46.2,218.0,22.0,10.1,44.0,1.33,17.9
3,Saturnin Allagbé,GK,Dijon,fr Ligue 1,26.0,12.0,12.0,1080.0,12.0,30.0,...,-0.63,80.0,211.0,37.9,105.0,4.0,3.8,13.0,1.08,14.8
4,Nícolas Andrade,GK,Udinese,it Serie A,32.0,2.0,2.0,180.0,2.0,5.0,...,-0.48,6.0,13.0,46.2,16.0,0.0,0.0,0.0,0.00,15.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,Rubén Yáñez,GK,Getafe,es La Liga,26.0,10.0,10.0,900.0,10.0,12.0,...,-0.04,89.0,203.0,43.8,72.0,5.0,6.9,7.0,0.70,15.2
204,Yoel,GK,Eibar,es La Liga,31.0,4.0,3.0,300.0,3.3,3.0,...,-0.24,39.0,74.0,52.7,11.0,1.0,9.1,8.0,2.40,17.7
205,Robin Zentner,GK,Mainz 05,de Bundesliga,25.0,31.0,31.0,2790.0,31.0,46.0,...,-0.14,166.0,501.0,33.1,294.0,28.0,9.5,19.0,0.61,14.0
206,Ron-Robert Zieler,GK,Köln,de Bundesliga,31.0,1.0,0.0,51.0,0.6,1.0,...,-0.46,6.0,11.0,54.5,10.0,0.0,0.0,0.0,0.00,11.8
207,Jeroen Zoet,GK,Spezia,it Serie A,29.0,7.0,7.0,603.0,6.7,12.0,...,-0.06,56.0,128.0,43.8,60.0,6.0,10.0,8.0,1.19,15.1

In [62]:
# Load transfermarkt dataset
transfer_df = pd.read_csv("top5_league_market_values.csv", index_col=0)
transfer_df = transfer_df.rename(columns={"Players": "Player"})

# Delete Duplicate Players
transfer_df.drop_duplicates(subset ="Player", inplace = True)
print(transfer_df.nunique())
print(transfer_df.shape)

Player    2930
Values     106
Team        98
dtype: int64
(2930, 3)

In [53]:
duplicate_series = combined_df.duplicated(subset=['Player'].nunique()"Player", keep=False)
combined_df[duplicate_series]

,Player,Pos,Squad,Comp,Age,MP,Starts,Min,90s,GA,...,/90,Cmp,Att,Cmp%,Opp,Stp,Stp%,#OPA,#OPA/90,AvgDist
72,Alfred Gomis,GK,Rennes,fr Ligue 1,26.0,22.0,22.0,1980.0,22.0,25.0,...,0.01,99.0,229.0,43.2,158.0,17.0,10.8,17.0,0.77,15.3
73,Alfred Gomis,GK,Dijon,fr Ligue 1,26.0,5.0,5.0,450.0,5.0,10.0,...,0.17,28.0,94.0,29.8,78.0,8.0,10.3,3.0,0.60,12.8
114,Edouard Mendy,GK,Rennes,fr Ligue 1,28.0,1.0,1.0,90.0,1.0,1.0,...,-0.44,7.0,12.0,58.3,6.0,1.0,16.7,0.0,0.00,10.0
115,Edouard Mendy,GK,Chelsea,eng Premier League,28.0,31.0,31.0,2745.0,30.5,25.0,...,0.00,126.0,265.0,47.5,207.0,13.0,6.3,20.0,0.66,15.3
170,Mathew Ryan,GK,Brighton,eng Premier League,28.0,11.0,11.0,990.0,11.0,19.0,...,-0.29,57.0,141.0,40.4,103.0,7.0,6.8,6.0,0.55,14.4
171,Mathew Ryan,GK,Arsenal,eng Premier League,28.0,3.0,3.0,270.0,3.0,2.0,...,0.73,6.0,11.0,54.5,20.0,4.0,20.0,1.0,0.33,13.4

In [54]:
# From above delete Alfred Gomis (Dijon), Edouard Mendy (Rennes), Mathew Ryan (Arsenal)
combined_df.drop(index=[73, 114, 171], inplace=True)

In [59]:
combined_df

,Player,Pos,Squad,Comp,Age,MP,Starts,Min,90s,GA,...,/90,Cmp,Att,Cmp%,Opp,Stp,Stp%,#OPA,#OPA/90,AvgDist
0,Adrián,GK,Liverpool,eng Premier League,33.0,3.0,3.0,270.0,3.0,9.0,...,-0.36,12.0,32.0,37.5,29.0,2.0,6.9,1.0,0.33,13.2
1,Rúnar Alex Rúnarsson,GK,Arsenal,eng Premier League,25.0,1.0,0.0,16.0,0.2,0.0,...,0.50,0.0,3.0,0.0,4.0,0.0,0.0,0.0,0.00,17.5
2,Alisson,GK,Liverpool,eng Premier League,27.0,33.0,33.0,2970.0,33.0,32.0,...,0.18,127.0,275.0,46.2,218.0,22.0,10.1,44.0,1.33,17.9
3,Saturnin Allagbé,GK,Dijon,fr Ligue 1,26.0,12.0,12.0,1080.0,12.0,30.0,...,-0.63,80.0,211.0,37.9,105.0,4.0,3.8,13.0,1.08,14.8
4,Nícolas Andrade,GK,Udinese,it Serie A,32.0,2.0,2.0,180.0,2.0,5.0,...,-0.48,6.0,13.0,46.2,16.0,0.0,0.0,0.0,0.00,15.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,Rubén Yáñez,GK,Getafe,es La Liga,26.0,10.0,10.0,900.0,10.0,12.0,...,-0.04,89.0,203.0,43.8,72.0,5.0,6.9,7.0,0.70,15.2
204,Yoel,GK,Eibar,es La Liga,31.0,4.0,3.0,300.0,3.3,3.0,...,-0.24,39.0,74.0,52.7,11.0,1.0,9.1,8.0,2.40,17.7
205,Robin Zentner,GK,Mainz 05,de Bundesliga,25.0,31.0,31.0,2790.0,31.0,46.0,...,-0.14,166.0,501.0,33.1,294.0,28.0,9.5,19.0,0.61,14.0
206,Ron-Robert Zieler,GK,Köln,de Bundesliga,31.0,1.0,0.0,51.0,0.6,1.0,...,-0.46,6.0,11.0,54.5,10.0,0.0,0.0,0.0,0.00,11.8
207,Jeroen Zoet,GK,Spezia,it Serie A,29.0,7.0,7.0,603.0,6.7,12.0,...,-0.06,56.0,128.0,43.8,60.0,6.0,10.0,8.0,1.19,15.1

In [72]:
# Combine transfermarkt data and fb reference data
final_df = pd.merge(combined_df, transfer_df, on="Player")
final_df.fillna(0, inplace=True)

In [73]:
final_df.describe()

,Age,MP,Starts,Min,90s,GA,GA90,SoTA,Saves,Save%,...,Cmp,Att,Cmp%,Opp,Stp,Stp%,#OPA,#OPA/90,AvgDist,Values
count,151.000000,151.000000,151.000000,151.000000,151.000000,151.000000,151.000000,151.000000,151.000000,151.000000,...,151.000000,151.000000,151.000000,151.000000,151.000000,151.000000,151.000000,151.000000,151.000000,1.510000e+02
mean,27.748344,18.172185,18.026490,1622.403974,18.027152,25.364238,1.507483,71.529801,48.900662,66.358940,...,114.536424,281.920530,38.831126,155.794702,11.350993,6.376821,11.682119,0.605960,14.052318,7.962616e+06
std,4.783609,14.406370,14.528568,1300.858369,14.454540,21.140950,0.726578,60.060393,41.953268,15.379004,...,105.009509,255.278189,11.934997,129.753629,10.866584,3.922881,11.667831,0.518753,3.205554,1.366613e+07
min,18.000000,1.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.500000e+04
25%,24.000000,3.000000,3.000000,270.000000,3.000000,6.000000,1.105000,14.500000,9.000000,62.250000,...,15.000000,36.500000,33.450000,27.500000,1.000000,4.700000,1.000000,0.310000,12.900000,8.800000e+05
50%,27.000000,16.000000,16.000000,1440.000000,16.000000,23.000000,1.450000,56.000000,37.000000,67.900000,...,91.000000,211.000000,39.700000,129.000000,9.000000,6.500000,9.000000,0.550000,14.100000,2.750000e+06
75%,31.000000,32.500000,32.500000,2925.000000,32.500000,43.000000,1.765000,124.500000,85.500000,72.850000,...,193.000000,467.000000,44.350000,284.000000,19.500000,8.850000,19.500000,0.760000,15.300000,8.800000e+06
max,39.000000,38.000000,38.000000,3420.000000,38.000000,76.000000,4.520000,228.000000,161.000000,100.000000,...,488.000000,1038.000000,100.000000,427.000000,42.000000,20.000000,53.000000,3.910000,31.000000,7.700000e+07

In [77]:
final_df.to_csv('clean_goalkeepers.csv')